version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file: ./.env
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: ${MYSQLDB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysqldb

volumes:
  mysql_data: